//------------------------------------------------------------------------------
// <auto-generated>
//     Generado por la herramienta de generación de código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEstacionamiento.WebForms
{
    public partial class Bitacora
    {
        protected global::System.Web.UI.WebControls.TextBox txtDesde;
        protected global::System.Web.UI.WebControls.TextBox txtHasta;
        protected global::System.Web.UI.WebControls.DropDownList ddlNivel;
        protected global::System.Web.UI.WebControls.TextBox txtMensaje;
        protected global::System.Web.UI.WebControls.Button btnBuscar;
        protected global::System.Web.UI.WebControls.GridView gvLogs;
    }
}
