//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEstacionamiento.WebForms
{
    public partial class PanelAdministrador
    {
        protected global::System.Web.UI.WebControls.TextBox txtRuta;
        protected global::System.Web.UI.WebControls.Button btnBackup;
        protected global::System.Web.UI.WebControls.Button btnRestore;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
    }
}
